//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://operaize.com/in/master")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://operaize.com/in/master", IsNullable=false)]
public partial class MasterData : object, System.ComponentModel.INotifyPropertyChanged {
    
    private LocationType[] locationsField;
    
    private MaterialType[] materialsField;
    
    private ResourceType[] resourcesField;
    
    private ResourceGroupType[] resourceGroupsField;
    
    private StorageType[] storagesField;
    
    private BOMProducedType[] billsOfMaterialsField;
    
    private RoutingProducedType[] routingsField;
    
    private BOMRoutingProducedType[] bOMRoutingAlternativesField;
    
    private CalendarType[] calendarsField;
    
    private ShiftType[] shiftsField;
    
    private ChangeOverMatrixType[] changeoverMatricesField;
    
    private string masterIDField;
    
    private System.DateTime timeStampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Location", IsNullable=false)]
    public LocationType[] Locations {
        get {
            return this.locationsField;
        }
        set {
            this.locationsField = value;
            this.RaisePropertyChanged("Locations");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Material", IsNullable=false)]
    public MaterialType[] Materials {
        get {
            return this.materialsField;
        }
        set {
            this.materialsField = value;
            this.RaisePropertyChanged("Materials");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable=false)]
    public ResourceType[] Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
            this.RaisePropertyChanged("Resources");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ResourceGroup", IsNullable=false)]
    public ResourceGroupType[] ResourceGroups {
        get {
            return this.resourceGroupsField;
        }
        set {
            this.resourceGroupsField = value;
            this.RaisePropertyChanged("ResourceGroups");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Storage", IsNullable=false)]
    public StorageType[] Storages {
        get {
            return this.storagesField;
        }
        set {
            this.storagesField = value;
            this.RaisePropertyChanged("Storages");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Produced", IsNullable=false)]
    public BOMProducedType[] BillsOfMaterials {
        get {
            return this.billsOfMaterialsField;
        }
        set {
            this.billsOfMaterialsField = value;
            this.RaisePropertyChanged("BillsOfMaterials");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Produced", IsNullable=false)]
    public RoutingProducedType[] Routings {
        get {
            return this.routingsField;
        }
        set {
            this.routingsField = value;
            this.RaisePropertyChanged("Routings");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Produced", IsNullable=false)]
    public BOMRoutingProducedType[] BOMRoutingAlternatives {
        get {
            return this.bOMRoutingAlternativesField;
        }
        set {
            this.bOMRoutingAlternativesField = value;
            this.RaisePropertyChanged("BOMRoutingAlternatives");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Calendar", IsNullable=false)]
    public CalendarType[] Calendars {
        get {
            return this.calendarsField;
        }
        set {
            this.calendarsField = value;
            this.RaisePropertyChanged("Calendars");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Shift", IsNullable=false)]
    public ShiftType[] Shifts {
        get {
            return this.shiftsField;
        }
        set {
            this.shiftsField = value;
            this.RaisePropertyChanged("Shifts");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ChangeOverMatrix", IsNullable=false)]
    public ChangeOverMatrixType[] ChangeoverMatrices {
        get {
            return this.changeoverMatricesField;
        }
        set {
            this.changeoverMatricesField = value;
            this.RaisePropertyChanged("ChangeoverMatrices");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MasterID {
        get {
            return this.masterIDField;
        }
        set {
            this.masterIDField = value;
            this.RaisePropertyChanged("MasterID");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime TimeStamp {
        get {
            return this.timeStampField;
        }
        set {
            this.timeStampField = value;
            this.RaisePropertyChanged("TimeStamp");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class LocationType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ChangeOverMatrixType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string locationRefField;
    
    private string resourceRefField;
    
    private string materialFromRefField;
    
    private string materialToRefField;
    
    private double setupTimeField;
    
    private TimeUnitType timeUnitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationRef {
        get {
            return this.locationRefField;
        }
        set {
            this.locationRefField = value;
            this.RaisePropertyChanged("LocationRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ResourceRef {
        get {
            return this.resourceRefField;
        }
        set {
            this.resourceRefField = value;
            this.RaisePropertyChanged("ResourceRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialFromRef {
        get {
            return this.materialFromRefField;
        }
        set {
            this.materialFromRefField = value;
            this.RaisePropertyChanged("MaterialFromRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialToRef {
        get {
            return this.materialToRefField;
        }
        set {
            this.materialToRefField = value;
            this.RaisePropertyChanged("MaterialToRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double SetupTime {
        get {
            return this.setupTimeField;
        }
        set {
            this.setupTimeField = value;
            this.RaisePropertyChanged("SetupTime");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TimeUnitType TimeUnit {
        get {
            return this.timeUnitField;
        }
        set {
            this.timeUnitField = value;
            this.RaisePropertyChanged("TimeUnit");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public enum TimeUnitType {
    
    /// <remarks/>
    sec,
    
    /// <remarks/>
    min,
    
    /// <remarks/>
    h,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ShiftType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string idField;
    
    private System.DateTime startField;
    
    private float durationField;
    
    private TimeUnitType timeUnitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
            this.RaisePropertyChanged("Start");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
            this.RaisePropertyChanged("Duration");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TimeUnitType TimeUnit {
        get {
            return this.timeUnitField;
        }
        set {
            this.timeUnitField = value;
            this.RaisePropertyChanged("TimeUnit");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ShiftRefType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
            this.RaisePropertyChanged("Ref");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class DayType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ShiftRefType[] shiftField;
    
    private string numberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Shift")]
    public ShiftRefType[] Shift {
        get {
            return this.shiftField;
        }
        set {
            this.shiftField = value;
            this.RaisePropertyChanged("Shift");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
            this.RaisePropertyChanged("Number");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class CalendarType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private DayType[] dayField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Day")]
    public DayType[] Day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
            this.RaisePropertyChanged("Day");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class BOMRoutingAlternativeType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string priorityField;
    
    private string bOMRefField;
    
    private string routingRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
            this.RaisePropertyChanged("Priority");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BOMRef {
        get {
            return this.bOMRefField;
        }
        set {
            this.bOMRefField = value;
            this.RaisePropertyChanged("BOMRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RoutingRef {
        get {
            return this.routingRefField;
        }
        set {
            this.routingRefField = value;
            this.RaisePropertyChanged("RoutingRef");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class BOMRoutingProducedType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private BOMRoutingAlternativeType[] bOMRoutingAlternativeField;
    
    private string materialRefField;
    
    private string locationRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BOMRoutingAlternative")]
    public BOMRoutingAlternativeType[] BOMRoutingAlternative {
        get {
            return this.bOMRoutingAlternativeField;
        }
        set {
            this.bOMRoutingAlternativeField = value;
            this.RaisePropertyChanged("BOMRoutingAlternative");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialRef {
        get {
            return this.materialRefField;
        }
        set {
            this.materialRefField = value;
            this.RaisePropertyChanged("MaterialRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationRef {
        get {
            return this.locationRefField;
        }
        set {
            this.locationRefField = value;
            this.RaisePropertyChanged("LocationRef");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class PhaseType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private OperationResGroupType[] resourcesField;
    
    private PhaseTypeName nameField;
    
    private TimeUnitType timeUnitField;
    
    private uint durationField;
    
    private float linearField;
    
    private bool linearFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ResourceGroup", IsNullable=false)]
    public OperationResGroupType[] Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
            this.RaisePropertyChanged("Resources");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PhaseTypeName Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public TimeUnitType TimeUnit {
        get {
            return this.timeUnitField;
        }
        set {
            this.timeUnitField = value;
            this.RaisePropertyChanged("TimeUnit");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
            this.RaisePropertyChanged("Duration");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float Linear {
        get {
            return this.linearField;
        }
        set {
            this.linearField = value;
            this.RaisePropertyChanged("Linear");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LinearSpecified {
        get {
            return this.linearFieldSpecified;
        }
        set {
            this.linearFieldSpecified = value;
            this.RaisePropertyChanged("LinearSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class OperationResGroupType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string refField;
    
    private string priorityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
            this.RaisePropertyChanged("Ref");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
            this.RaisePropertyChanged("Priority");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://operaize.com/in/master")]
public enum PhaseTypeName {
    
    /// <remarks/>
    Queue,
    
    /// <remarks/>
    Setup,
    
    /// <remarks/>
    Processing,
    
    /// <remarks/>
    Teardown,
    
    /// <remarks/>
    Wait,
    
    /// <remarks/>
    Movement,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ConnectionType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string operationRefField;
    
    private bool gluedConnectionField;
    
    private PredSuccPhaseType startsWithPredecessorPhaseField;
    
    private bool startsWithPredecessorPhaseFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OperationRef {
        get {
            return this.operationRefField;
        }
        set {
            this.operationRefField = value;
            this.RaisePropertyChanged("OperationRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool GluedConnection {
        get {
            return this.gluedConnectionField;
        }
        set {
            this.gluedConnectionField = value;
            this.RaisePropertyChanged("GluedConnection");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PredSuccPhaseType StartsWithPredecessorPhase {
        get {
            return this.startsWithPredecessorPhaseField;
        }
        set {
            this.startsWithPredecessorPhaseField = value;
            this.RaisePropertyChanged("StartsWithPredecessorPhase");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StartsWithPredecessorPhaseSpecified {
        get {
            return this.startsWithPredecessorPhaseFieldSpecified;
        }
        set {
            this.startsWithPredecessorPhaseFieldSpecified = value;
            this.RaisePropertyChanged("StartsWithPredecessorPhaseSpecified");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public enum PredSuccPhaseType {
    
    /// <remarks/>
    Queue,
    
    /// <remarks/>
    Setup,
    
    /// <remarks/>
    Processing,
    
    /// <remarks/>
    Teardown,
    
    /// <remarks/>
    Wait,
    
    /// <remarks/>
    Movement,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ConnectionsType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ConnectionType[] predecessorField;
    
    private ConnectionType[] successorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Predecessor")]
    public ConnectionType[] Predecessor {
        get {
            return this.predecessorField;
        }
        set {
            this.predecessorField = value;
            this.RaisePropertyChanged("Predecessor");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Successor")]
    public ConnectionType[] Successor {
        get {
            return this.successorField;
        }
        set {
            this.successorField = value;
            this.RaisePropertyChanged("Successor");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class OperationType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private OperationResGroupType[] resourcesField;
    
    private ConnectionsType connectionsField;
    
    private PhaseType[] phasesField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ResourceGroup", IsNullable=false)]
    public OperationResGroupType[] Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
            this.RaisePropertyChanged("Resources");
        }
    }
    
    /// <remarks/>
    public ConnectionsType Connections {
        get {
            return this.connectionsField;
        }
        set {
            this.connectionsField = value;
            this.RaisePropertyChanged("Connections");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Phase", IsNullable=false)]
    public PhaseType[] Phases {
        get {
            return this.phasesField;
        }
        set {
            this.phasesField = value;
            this.RaisePropertyChanged("Phases");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class RoutingType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private OperationType[] operationField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Operation")]
    public OperationType[] Operation {
        get {
            return this.operationField;
        }
        set {
            this.operationField = value;
            this.RaisePropertyChanged("Operation");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class RoutingProducedType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private RoutingType[] routingField;
    
    private string materialRefField;
    
    private string locationRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Routing")]
    public RoutingType[] Routing {
        get {
            return this.routingField;
        }
        set {
            this.routingField = value;
            this.RaisePropertyChanged("Routing");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialRef {
        get {
            return this.materialRefField;
        }
        set {
            this.materialRefField = value;
            this.RaisePropertyChanged("MaterialRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationRef {
        get {
            return this.locationRefField;
        }
        set {
            this.locationRefField = value;
            this.RaisePropertyChanged("LocationRef");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ConsumedType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string materialRefField;
    
    private float quantityPerField;
    
    private string operationRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialRef {
        get {
            return this.materialRefField;
        }
        set {
            this.materialRefField = value;
            this.RaisePropertyChanged("MaterialRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float QuantityPer {
        get {
            return this.quantityPerField;
        }
        set {
            this.quantityPerField = value;
            this.RaisePropertyChanged("QuantityPer");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OperationRef {
        get {
            return this.operationRefField;
        }
        set {
            this.operationRefField = value;
            this.RaisePropertyChanged("OperationRef");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class BOMType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ConsumedType[] consumedField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Consumed")]
    public ConsumedType[] Consumed {
        get {
            return this.consumedField;
        }
        set {
            this.consumedField = value;
            this.RaisePropertyChanged("Consumed");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class BOMProducedType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private BOMType[] billOfMaterialsField;
    
    private string materialRefField;
    
    private float quantityPerField;
    
    private string locationRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BillOfMaterials")]
    public BOMType[] BillOfMaterials {
        get {
            return this.billOfMaterialsField;
        }
        set {
            this.billOfMaterialsField = value;
            this.RaisePropertyChanged("BillOfMaterials");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialRef {
        get {
            return this.materialRefField;
        }
        set {
            this.materialRefField = value;
            this.RaisePropertyChanged("MaterialRef");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float QuantityPer {
        get {
            return this.quantityPerField;
        }
        set {
            this.quantityPerField = value;
            this.RaisePropertyChanged("QuantityPer");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationRef {
        get {
            return this.locationRefField;
        }
        set {
            this.locationRefField = value;
            this.RaisePropertyChanged("LocationRef");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class StorageType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string idField;
    
    private string locationRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationRef {
        get {
            return this.locationRefField;
        }
        set {
            this.locationRefField = value;
            this.RaisePropertyChanged("LocationRef");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ResourceGroupResType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string refField;
    
    private string requiredAmountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
            this.RaisePropertyChanged("Ref");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string RequiredAmount {
        get {
            return this.requiredAmountField;
        }
        set {
            this.requiredAmountField = value;
            this.RaisePropertyChanged("RequiredAmount");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ResourceGroupType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private ResourceGroupResType[] resourceField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Resource")]
    public ResourceGroupResType[] Resource {
        get {
            return this.resourceField;
        }
        set {
            this.resourceField = value;
            this.RaisePropertyChanged("Resource");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class ResourceType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string idField;
    
    private string uOMField;
    
    private string locationRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UOM {
        get {
            return this.uOMField;
        }
        set {
            this.uOMField = value;
            this.RaisePropertyChanged("UOM");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LocationRef {
        get {
            return this.locationRefField;
        }
        set {
            this.locationRefField = value;
            this.RaisePropertyChanged("LocationRef");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class MaterialStorageType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
            this.RaisePropertyChanged("Ref");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
public partial class MaterialType : object, System.ComponentModel.INotifyPropertyChanged {
    
    private MaterialStorageType[] storageField;
    
    private string idField;
    
    private string uOMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Storage")]
    public MaterialStorageType[] Storage {
        get {
            return this.storageField;
        }
        set {
            this.storageField = value;
            this.RaisePropertyChanged("Storage");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UOM {
        get {
            return this.uOMField;
        }
        set {
            this.uOMField = value;
            this.RaisePropertyChanged("UOM");
        }
    }
    
    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
    
    protected void RaisePropertyChanged(string propertyName) {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null)) {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
