// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.0.0. www.xsd2code.com
//    {"TargetFramework":"NetCore","NameSpace":"GraphQl.Common","Properties":{},"XmlAttribute":{"Enabled":true},"ClassParams":{},"Miscellaneous":{}}
//  </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;

#pragma warning disable
namespace GraphQl.Common
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Runtime.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Xml;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType=true, Namespace="http://operaize.com/in/master")]
    [XmlRootAttribute(Namespace="http://operaize.com/in/master", IsNullable=false)]
    public partial class MasterData
    {
        #region Private fields
        private List<LocationType> _locations;
        private List<MaterialType> _materials;
        private List<ResourceType> _resources;
        private List<ResourceGroupType> _resourceGroups;
        private List<StorageType> _storages;
        private List<BOMProducedType> _billsOfMaterials;
        private List<RoutingProducedType> _routings;
        private List<BOMRoutingProducedType> _bOMRoutingAlternatives;
        private List<CalendarType> _calendars;
        private List<ShiftType> _shifts;
        private List<ChangeOverMatrixType> _changeoverMatrices;
        private string _masterID;
        private System.DateTime _timeStamp;
        #endregion
        
        public MasterData()
        {
            _changeoverMatrices = new List<ChangeOverMatrixType>();
            _shifts = new List<ShiftType>();
            _calendars = new List<CalendarType>();
            _bOMRoutingAlternatives = new List<BOMRoutingProducedType>();
            _routings = new List<RoutingProducedType>();
            _billsOfMaterials = new List<BOMProducedType>();
            _storages = new List<StorageType>();
            _resourceGroups = new List<ResourceGroupType>();
            _resources = new List<ResourceType>();
            _materials = new List<MaterialType>();
            _locations = new List<LocationType>();
        }
        
        [XmlArrayItemAttribute("Location", IsNullable=false)]
        public List<LocationType> Locations
        {
            get
            {
                return _locations;
            }
            set
            {
                _locations = value;
            }
        }
        
        [XmlArrayItemAttribute("Material", IsNullable=false)]
        public List<MaterialType> Materials
        {
            get
            {
                return _materials;
            }
            set
            {
                _materials = value;
            }
        }
        
        [XmlArrayItemAttribute("Resource", IsNullable=false)]
        public List<ResourceType> Resources
        {
            get
            {
                return _resources;
            }
            set
            {
                _resources = value;
            }
        }
        
        [XmlArrayItemAttribute("ResourceGroup", IsNullable=false)]
        public List<ResourceGroupType> ResourceGroups
        {
            get
            {
                return _resourceGroups;
            }
            set
            {
                _resourceGroups = value;
            }
        }
        
        [XmlArrayItemAttribute("Storage", IsNullable=false)]
        public List<StorageType> Storages
        {
            get
            {
                return _storages;
            }
            set
            {
                _storages = value;
            }
        }
        
        [XmlArrayItemAttribute("Produced", IsNullable=false)]
        public List<BOMProducedType> BillsOfMaterials
        {
            get
            {
                return _billsOfMaterials;
            }
            set
            {
                _billsOfMaterials = value;
            }
        }
        
        [XmlArrayItemAttribute("Produced", IsNullable=false)]
        public List<RoutingProducedType> Routings
        {
            get
            {
                return _routings;
            }
            set
            {
                _routings = value;
            }
        }
        
        [XmlArrayItemAttribute("Produced", IsNullable=false)]
        public List<BOMRoutingProducedType> BOMRoutingAlternatives
        {
            get
            {
                return _bOMRoutingAlternatives;
            }
            set
            {
                _bOMRoutingAlternatives = value;
            }
        }
        
        [XmlArrayItemAttribute("Calendar", IsNullable=false)]
        public List<CalendarType> Calendars
        {
            get
            {
                return _calendars;
            }
            set
            {
                _calendars = value;
            }
        }
        
        [XmlArrayItemAttribute("Shift", IsNullable=false)]
        public List<ShiftType> Shifts
        {
            get
            {
                return _shifts;
            }
            set
            {
                _shifts = value;
            }
        }
        
        [XmlArrayItemAttribute("ChangeOverMatrix", IsNullable=false)]
        public List<ChangeOverMatrixType> ChangeoverMatrices
        {
            get
            {
                return _changeoverMatrices;
            }
            set
            {
                _changeoverMatrices = value;
            }
        }
        
        [XmlAttribute]
        public string MasterID
        {
            get
            {
                return _masterID;
            }
            set
            {
                _masterID = value;
            }
        }
        
        [XmlAttribute]
        public System.DateTime TimeStamp
        {
            get
            {
                return _timeStamp;
            }
            set
            {
                _timeStamp = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class LocationType
    {
        #region Private fields
        private string _id;
        #endregion
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ChangeOverMatrixType
    {
        #region Private fields
        private string _locationRef;
        private string _resourceRef;
        private string _materialFromRef;
        private string _materialToRef;
        private double _setupTime;
        private TimeUnitType _timeUnit;
        #endregion
        
        [XmlAttribute]
        public string LocationRef
        {
            get
            {
                return _locationRef;
            }
            set
            {
                _locationRef = value;
            }
        }
        
        [XmlAttribute]
        public string ResourceRef
        {
            get
            {
                return _resourceRef;
            }
            set
            {
                _resourceRef = value;
            }
        }
        
        [XmlAttribute]
        public string MaterialFromRef
        {
            get
            {
                return _materialFromRef;
            }
            set
            {
                _materialFromRef = value;
            }
        }
        
        [XmlAttribute]
        public string MaterialToRef
        {
            get
            {
                return _materialToRef;
            }
            set
            {
                _materialToRef = value;
            }
        }
        
        [XmlAttribute]
        public double SetupTime
        {
            get
            {
                return _setupTime;
            }
            set
            {
                _setupTime = value;
            }
        }
        
        [XmlAttribute]
        public TimeUnitType TimeUnit
        {
            get
            {
                return _timeUnit;
            }
            set
            {
                _timeUnit = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public enum TimeUnitType
    {
        sec,
        min,
        h,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ShiftType
    {
        #region Private fields
        private string _id;
        private System.DateTime _start;
        private float _duration;
        private TimeUnitType _timeUnit;
        #endregion
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        
        [XmlAttribute(DataType="time")]
        public System.DateTime Start
        {
            get
            {
                return _start;
            }
            set
            {
                _start = value;
            }
        }
        
        [XmlAttribute]
        public float Duration
        {
            get
            {
                return _duration;
            }
            set
            {
                _duration = value;
            }
        }
        
        [XmlAttribute]
        public TimeUnitType TimeUnit
        {
            get
            {
                return _timeUnit;
            }
            set
            {
                _timeUnit = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ShiftRefType
    {
        #region Private fields
        private string _ref;
        #endregion
        
        [XmlAttribute]
        public string Ref
        {
            get
            {
                return _ref;
            }
            set
            {
                _ref = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class DayType
    {
        #region Private fields
        private List<ShiftRefType> _shift;
        private string _number;
        #endregion
        
        public DayType()
        {
            _shift = new List<ShiftRefType>();
        }
        
        [XmlElement("Shift")]
        public List<ShiftRefType> Shift
        {
            get
            {
                return _shift;
            }
            set
            {
                _shift = value;
            }
        }
        
        [XmlAttribute(DataType="positiveInteger")]
        public string Number
        {
            get
            {
                return _number;
            }
            set
            {
                _number = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class CalendarType
    {
        #region Private fields
        private List<DayType> _day;
        private string _id;
        #endregion
        
        public CalendarType()
        {
            _day = new List<DayType>();
        }
        
        [XmlElement("Day")]
        public List<DayType> Day
        {
            get
            {
                return _day;
            }
            set
            {
                _day = value;
            }
        }
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class BOMRoutingAlternativeType
    {
        #region Private fields
        private string _priority;
        private string _bOMRef;
        private string _routingRef;
        #endregion
        
        [XmlAttribute(DataType="positiveInteger")]
        public string Priority
        {
            get
            {
                return _priority;
            }
            set
            {
                _priority = value;
            }
        }
        
        [XmlAttribute]
        public string BOMRef
        {
            get
            {
                return _bOMRef;
            }
            set
            {
                _bOMRef = value;
            }
        }
        
        [XmlAttribute]
        public string RoutingRef
        {
            get
            {
                return _routingRef;
            }
            set
            {
                _routingRef = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class BOMRoutingProducedType
    {
        #region Private fields
        private List<BOMRoutingAlternativeType> _bOMRoutingAlternative;
        private string _materialRef;
        private string _locationRef;
        #endregion
        
        public BOMRoutingProducedType()
        {
            _bOMRoutingAlternative = new List<BOMRoutingAlternativeType>();
        }
        
        [XmlElement("BOMRoutingAlternative")]
        public List<BOMRoutingAlternativeType> BOMRoutingAlternative
        {
            get
            {
                return _bOMRoutingAlternative;
            }
            set
            {
                _bOMRoutingAlternative = value;
            }
        }
        
        [XmlAttribute]
        public string MaterialRef
        {
            get
            {
                return _materialRef;
            }
            set
            {
                _materialRef = value;
            }
        }
        
        [XmlAttribute]
        public string LocationRef
        {
            get
            {
                return _locationRef;
            }
            set
            {
                _locationRef = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class PhaseType
    {
        #region Private fields
        private List<OperationResGroupType> _resources;
        private PhaseTypeName _name;
        private TimeUnitType _timeUnit;
        private uint _duration;
        private float _linear;
        #endregion
        
        public PhaseType()
        {
            _resources = new List<OperationResGroupType>();
        }
        
        [XmlArrayItemAttribute("ResourceGroup", IsNullable=false)]
        public List<OperationResGroupType> Resources
        {
            get
            {
                return _resources;
            }
            set
            {
                _resources = value;
            }
        }
        
        [XmlAttribute]
        public PhaseTypeName Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
        
        [XmlAttribute]
        public TimeUnitType TimeUnit
        {
            get
            {
                return _timeUnit;
            }
            set
            {
                _timeUnit = value;
            }
        }
        
        [XmlAttribute]
        public uint Duration
        {
            get
            {
                return _duration;
            }
            set
            {
                _duration = value;
            }
        }
        
        [XmlAttribute]
        public float Linear
        {
            get
            {
                return _linear;
            }
            set
            {
                _linear = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class OperationResGroupType
    {
        #region Private fields
        private string _ref;
        private string _priority;
        #endregion
        
        [XmlAttribute]
        public string Ref
        {
            get
            {
                return _ref;
            }
            set
            {
                _ref = value;
            }
        }
        
        [XmlAttribute(DataType="positiveInteger")]
        public string Priority
        {
            get
            {
                return _priority;
            }
            set
            {
                _priority = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [XmlTypeAttribute(AnonymousType=true, Namespace="http://operaize.com/in/master")]
    public enum PhaseTypeName
    {
        Queue,
        Setup,
        Processing,
        Teardown,
        Wait,
        Movement,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ConnectionType
    {
        #region Private fields
        private string _operationRef;
        private bool _gluedConnection;
        private PredSuccPhaseType _startsWithPredecessorPhase;
        #endregion
        
        [XmlAttribute]
        public string OperationRef
        {
            get
            {
                return _operationRef;
            }
            set
            {
                _operationRef = value;
            }
        }
        
        [XmlAttribute]
        public bool GluedConnection
        {
            get
            {
                return _gluedConnection;
            }
            set
            {
                _gluedConnection = value;
            }
        }
        
        [XmlAttribute]
        public PredSuccPhaseType StartsWithPredecessorPhase
        {
            get
            {
                return _startsWithPredecessorPhase;
            }
            set
            {
                _startsWithPredecessorPhase = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public enum PredSuccPhaseType
    {
        Queue,
        Setup,
        Processing,
        Teardown,
        Wait,
        Movement,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ConnectionsType
    {
        #region Private fields
        private List<ConnectionType> _predecessor;
        private List<ConnectionType> _successor;
        #endregion
        
        public ConnectionsType()
        {
            _successor = new List<ConnectionType>();
            _predecessor = new List<ConnectionType>();
        }
        
        [XmlElement("Predecessor")]
        public List<ConnectionType> Predecessor
        {
            get
            {
                return _predecessor;
            }
            set
            {
                _predecessor = value;
            }
        }
        
        [XmlElement("Successor")]
        public List<ConnectionType> Successor
        {
            get
            {
                return _successor;
            }
            set
            {
                _successor = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class OperationType
    {
        #region Private fields
        private List<OperationResGroupType> _resources;
        private ConnectionsType _connections;
        private List<PhaseType> _phases;
        private string _id;
        #endregion
        
        public OperationType()
        {
            _phases = new List<PhaseType>();
            _connections = new ConnectionsType();
            _resources = new List<OperationResGroupType>();
        }
        
        [XmlArrayItemAttribute("ResourceGroup", IsNullable=false)]
        public List<OperationResGroupType> Resources
        {
            get
            {
                return _resources;
            }
            set
            {
                _resources = value;
            }
        }
        
        public ConnectionsType Connections
        {
            get
            {
                return _connections;
            }
            set
            {
                _connections = value;
            }
        }
        
        [XmlArrayItemAttribute("Phase", IsNullable=false)]
        public List<PhaseType> Phases
        {
            get
            {
                return _phases;
            }
            set
            {
                _phases = value;
            }
        }
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class RoutingType
    {
        #region Private fields
        private List<OperationType> _operation;
        private string _id;
        #endregion
        
        public RoutingType()
        {
            _operation = new List<OperationType>();
        }
        
        [XmlElement("Operation")]
        public List<OperationType> Operation
        {
            get
            {
                return _operation;
            }
            set
            {
                _operation = value;
            }
        }
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class RoutingProducedType
    {
        #region Private fields
        private List<RoutingType> _routing;
        private string _materialRef;
        private string _locationRef;
        #endregion
        
        public RoutingProducedType()
        {
            _routing = new List<RoutingType>();
        }
        
        [XmlElement("Routing")]
        public List<RoutingType> Routing
        {
            get
            {
                return _routing;
            }
            set
            {
                _routing = value;
            }
        }
        
        [XmlAttribute]
        public string MaterialRef
        {
            get
            {
                return _materialRef;
            }
            set
            {
                _materialRef = value;
            }
        }
        
        [XmlAttribute]
        public string LocationRef
        {
            get
            {
                return _locationRef;
            }
            set
            {
                _locationRef = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ConsumedType
    {
        #region Private fields
        private string _materialRef;
        private float _quantityPer;
        private string _operationRef;
        #endregion
        
        [XmlAttribute]
        public string MaterialRef
        {
            get
            {
                return _materialRef;
            }
            set
            {
                _materialRef = value;
            }
        }
        
        [XmlAttribute]
        public float QuantityPer
        {
            get
            {
                return _quantityPer;
            }
            set
            {
                _quantityPer = value;
            }
        }
        
        [XmlAttribute]
        public string OperationRef
        {
            get
            {
                return _operationRef;
            }
            set
            {
                _operationRef = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class BOMType
    {
        #region Private fields
        private List<ConsumedType> _consumed;
        private string _id;
        #endregion
        
        public BOMType()
        {
            _consumed = new List<ConsumedType>();
        }
        
        [XmlElement("Consumed")]
        public List<ConsumedType> Consumed
        {
            get
            {
                return _consumed;
            }
            set
            {
                _consumed = value;
            }
        }
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    [Keyless]
    public partial class BOMProducedType
    {
        #region Private fields
        private List<BOMType> _billOfMaterials;
        private string _materialRef;
        private float _quantityPer;
        private string _locationRef;
        #endregion
        
        public BOMProducedType()
        {
            _billOfMaterials = new List<BOMType>();
        }
        
        [XmlElement("BillOfMaterials")]
        public List<BOMType> BillOfMaterials
        {
            get
            {
                return _billOfMaterials;
            }
            set
            {
                _billOfMaterials = value;
            }
        }
        
        [XmlAttribute]
        public string MaterialRef
        {
            get
            {
                return _materialRef;
            }
            set
            {
                _materialRef = value;
            }
        }
        
        [XmlAttribute]
        public float QuantityPer
        {
            get
            {
                return _quantityPer;
            }
            set
            {
                _quantityPer = value;
            }
        }
        
        [XmlAttribute]
        public string LocationRef
        {
            get
            {
                return _locationRef;
            }
            set
            {
                _locationRef = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class StorageType
    {
        #region Private fields
        private string _id;
        private string _locationRef;
        #endregion
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        
        [XmlAttribute]
        public string LocationRef
        {
            get
            {
                return _locationRef;
            }
            set
            {
                _locationRef = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ResourceGroupResType
    {
        #region Private fields
        private string _ref;
        private string _requiredAmount;
        #endregion
        
        [XmlAttribute]
        public string Ref
        {
            get
            {
                return _ref;
            }
            set
            {
                _ref = value;
            }
        }
        
        [XmlAttribute(DataType="positiveInteger")]
        public string RequiredAmount
        {
            get
            {
                return _requiredAmount;
            }
            set
            {
                _requiredAmount = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ResourceGroupType
    {
        #region Private fields
        private List<ResourceGroupResType> _resource;
        private string _id;
        #endregion
        
        public ResourceGroupType()
        {
            _resource = new List<ResourceGroupResType>();
        }
        
        [XmlElement("Resource")]
        public List<ResourceGroupResType> Resource
        {
            get
            {
                return _resource;
            }
            set
            {
                _resource = value;
            }
        }
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class ResourceType
    {
        #region Private fields
        private string _id;
        private string _uOM;
        private string _locationRef;
        #endregion
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        
        [XmlAttribute]
        public string UOM
        {
            get
            {
                return _uOM;
            }
            set
            {
                _uOM = value;
            }
        }
        
        [XmlAttribute]
        public string LocationRef
        {
            get
            {
                return _locationRef;
            }
            set
            {
                _locationRef = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class MaterialStorageType
    {
        #region Private fields
        private string _ref;
        #endregion
        
        [XmlAttribute]
        public string Ref
        {
            get
            {
                return _ref;
            }
            set
            {
                _ref = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://operaize.com/in/master")]
    public partial class MaterialType
    {
        #region Private fields
        private List<MaterialStorageType> _storage;
        private string _id;
        private string _uOM;
        #endregion
        
        public MaterialType()
        {
            _storage = new List<MaterialStorageType>();
        }
        
        [XmlElement("Storage")]
        public List<MaterialStorageType> Storage
        {
            get
            {
                return _storage;
            }
            set
            {
                _storage = value;
            }
        }
        
        [XmlAttribute]
        public string ID
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
        
        [XmlAttribute]
        public string UOM
        {
            get
            {
                return _uOM;
            }
            set
            {
                _uOM = value;
            }
        }
    }
}
#pragma warning restore
